spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms_db
    username: lms_user
    password: lms_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Flyway handles schema creation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: "YOUR_SUPER_SECRET_KEY_WHICH_SHOULD_BE_AT_LEAST_32_BYTES_LONG_FOR_HMAC_SHA256"
  expiration-ms: 86400000 # 24 hours
  refresh-expiration-ms: 604800000 # 7 days
